### ISSUE TITLE
Dependency issues on graham

### ISSUE THREAD

**Issue by Bradley-Karat** [akhanf/snakedwi#20]
Creating a virtual environment and then installing snakedwi from github results in multiple dependency issues, ex. the package requirements specified by snakedwi for Pandas and Numpy are outside of the versions available on compute canada.

**Comment by kaitj** [comment]
@Bradley-Karat messaged about this earlier today and was testing this out - `poetry install` in a fresh environment resolved some of the versioning issues (in particular for `pandas` and `numpy`), but could not install `Pillow`. Had to finish the installation with `git+https...`. If using the `git+https...` method in a fresh environment, it would run into same issues mentioned above. 

More of an issue with Graham dependencies I think - would something like `pex` be helpful in resolving this?

**Comment by akhanf** [comment]
Ah, yeah getting the python packages built on graham is a pain, and to make life easier I sometimes pin versions to those that are already available on compute canada's wheelhouse, but I haven't done that in snakedwi yet, and probably also did an update recently that caused more issues..

What I found a reasonable solution is to keep my own wheelhouse, and build the wheels first, then point to the wheelhouse when building the packages, e.g.:
```
pip wheel -r requirements.txt -w /project/6050199/akhanf/opt/wheelhouse/wheels
pip install -r requirements.txt -f /project/6050199/akhanf/opt/wheelhouse/wheels
```
That way, can also build the venv on localscratch (SLURM_TMPDIR) on a compute node, which is much faster than building on scratch, project or home.. 

I have recently shifted over to using Peter's [kslurm](https://github.com/pvandyken/kslurm) tool which now has kpy that actually handles this sort of thing transparently, and also allows you to load and restore tarred up venvs.. 

In any case, I'm still building the last few wheels for snakedwi, but once that is done you could use my wheelhouse to install (`pip install ... -f /project/6050199/akhanf/opt/wheelhouse/wheels`). Installing from github I think would work here too I think.

Re: pex I ran into a snag with snakemake when `run: ` directives are used (and maybe same with `script:`?) where it wasn't activating the right python environment -- I feel like there should be a workaround for that built-in pex but I haven't found one (nor looked that hard..) or debugged this too heavily..

**Comment by akhanf** [comment]
as I finished writing this, my wheels finished building -- so you can try building from the above mentioned wheelhouse now

**Comment by kaitj** [comment]
Just tried to build from both `requirements.txt` and from git with your wheelhouse - both work! 

Haven't switched over to `kslurm` yet, but seems useful. Will take a closer look at it and probably start to switch too!

**Comment by akhanf** [comment]
Great! Yes, could probably do a demo in an upcoming lab meeting on kslurm/kpy etc..

**Comment by akhanf** [comment]
the other thing I have been meaning to do is actually move all of the extra python dependencies into rule-based dependencies so that you don't actually need to install anything to run the workflow as long as you have snakemake.  For that, can either do conda, venv (with snakeboost), or singularity, but am leaning towards singularity for maximal portability, although that might limit being able to deploy the app as monolithic container..  I'll try to make a github repo template for this (that will simply use poetry and build/deploy to docker with actions) to play around..

**Comment by akhanf** [comment]
as part of #23, I have removed almost all of the python dependencies from the project (ie all except for snakemake/snakebids), instead using a singularity container (https://github.com/akhanf/snakedwi-pythondeps) for the python-based rules. This should simplify the install process.
