### ISSUE TITLE
mrcat error in rule concat_degibbs_dwi

### ISSUE THREAD

**Issue by Bradley-Karat** [akhanf/snakedwi#26]
The rule "concat_degibbs_dwi" in prepdwi.smk outputs the error "mrcat: [ERROR] Expected at least 3 arguments (2 supplied)" where I suppose the input is meant to be all 3D volumes of degibbed images and the rule is supposed to concatenate all of them into one file. However the input into mrcat is the already fully combined degibbed file (i.e. a complete 4D file as output from mrdegibbs). Perhaps mrdegibbs handles the concatenation now?

**Comment by akhanf** [comment]
hmm might be a bug, let me check -- assuming you are running this on data with a single dwi image right?

**Comment by Bradley-Karat** [comment]
yup - single dwi per session

**Comment by akhanf** [comment]
Yep, was a bug, was trying to concat files when only one exists. I have a concat_or_cp_cmd function already in place for another rule so was an easy fix. Can you try again with PR #27 ?  (`git checkout degibbs_concat`) and let me know if you come across any other issues?

**Comment by akhanf** [comment]
I believe this is fixed, so closing this

**Comment by akhanf** [comment]
resolved in #23

**Comment by Bradley-Karat** [comment]
Ah sorry, forgot to update on this but yes this has been resolved!
